#!/bin/sh -e
#
# 2020 Marko Seric (marko.seric at ssrq-sds-fds.ch)
# 2020,2021,2023 Dennis Camera (dennis camera at riiengineering.ch)
#
# This file is part of the skonfig set __easy_rsa.
#
# This set is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This set is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this set. If not, see <http://www.gnu.org/licenses/>.
#

quote() {
	sed -e "s/'/'\\\\''/g" -e "1s/^/'/" -e "\$s/\$/'/" <<-EOF
	$*
	EOF
}
drop_awk_comments() { quote "$(sed '/^[[:blank:]]*#.*$/d;/^$/d' "$@")"; }
quote_nonnum() { sed 's/^.*[^0-9].*$/"&"/;q' "$@"; }


os=$(cat "${__global:?}/explorer/os")

state_is=$(cat "${__object:?}/explorer/state")

pki_dir="/${__object_id:?}"
vars_file="${pki_dir:?}/vars"

if test "${state_is}" = 'suspicious'
then
	printf "Directory %s exists, but doesn't look like a valid PKI.\n" "${pki_dir-}" >&2
	printf 'Please clean it up manually and try again.\n'
	exit 1
fi


case ${os}
in
	(debian|devuan)
		easyrsa_bin='/usr/share/easy-rsa/easyrsa'
		;;
	(openwrt)
		easyrsa_bin='easyrsa'
		;;
	(*)
		exit 1  # fail, OS whitelist should be in manifest
		;;
esac


################################################################################
# Create PKI directory structure

case ${state_is}
in
	(absent)
		printf '%s --batch --pki-dir=%s init-pki\n' \
			"${easyrsa_bin}" "$(quote "${pki_dir:?}")"
		;;
esac


################################################################################
# Update vars file

# Prepare the information to determine if the vars file needs to be updated,
# and act accordingly
vars_and_values=$(
	while read -r param variable
	do
		test -f "${__object:?}/parameter/${param}" || continue
		printf '%s %s\n' \
			"${variable}" \
			"$(quote_nonnum "${__object:?}/parameter/${param}")"
	done <"${__type:?}/files/param_mapping.txt" \
	| sort
)

if ! printf '%s\n' "${vars_and_values}" | cmp -s "${__object:?}/explorer/vars" -
then
	cat <<CODE
awk $(drop_awk_comments "${__type:?}/files/update_vars.awk") <<'EOF' $(quote "${vars_file}") >$(quote "${vars_file}.tmp") \\
 && cat $(quote "${vars_file}.tmp") >$(quote "${vars_file}") || exit
${vars_and_values}
EOF
rm -f $(quote "${vars_file}.tmp")
CODE
fi
