#!/bin/sh -e
#
# Returns the current state of the certificate:
#  - "valid" if the certificate exists and is valid.
#  - "expired" if the certificate exists but has expired.
#  - "unsigned" if there is a CSR, but it has not been signed
#  - "absent" if the certificate was revoked or was never signed.
#

base_dir=$(cat "${__object:?}/parameter/dir")
pki_dir="${base_dir}/pki"

# shellcheck disable=SC2015
test -f "${base_dir}/vars" && test -d "${pki_dir}"|| {
	echo 'no-pki'
	exit 0
}

cert_file="${pki_dir}/issued/${__object_id:?}.crt"
req_file="${pki_dir}/reqs/${__object_id:?}.req"

if test -f "${cert_file}"
then
	if openssl x509 -noout -in "${cert_file}" -checkend 0 >/dev/null
	then
		echo 'valid'
	else
		echo 'expired'
	fi
elif test -f "${req_file}"
then
	echo 'unsigned'
else
	echo 'absent'
fi
