#!/bin/sh -e
#
# 2020 Marko Seric (marko.seric@ssrq-sds-fds.ch)
#
# This file is part of cdist.
#
# cdist is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# cdist is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with cdist. If not, see <http://www.gnu.org/licenses/>.
#

# shellcheck disable=SC2154 # $__global will be supplied by cdist
os=$(cat "$__global/explorer/os")

case "$os" in
   (devuan|debian)
      __package easy-rsa --state present
   ;;
   (*)
      printf "Your operating system (%s) is currently not supported by this type (%s)\n" "$os" "${__type##*/}" >&2
      printf "Please contribute an implementation for it if you can.\n" >&2
      exit 1
   ;;
esac


pki_state=$(cat "${__object:?}/explorer/pki-presence")
if [ "${pki_state}" = "absent" ] && [ -z ${__cdist_dry_run+real_run} ]; then
   echo "No PKI found. Exiting" >&2
   exit 1
fi
