#!/bin/sh -e

# Return "present" if the CA is present, "absent" otherwise.

dir=$(cat "${__object:?}/parameter/dir")

test -d "${dir}" || {
	echo 'absent'
	exit 0
}

result='absent'

for dir in issued certs_by_serial
do
	if [ -d "${dir}/pki/${dir}" ]
	then
		result='present'
	fi
done

for file in serial index.txt index.txt.attr ca.crt private/ca.key
do
	if [ -f "${dir}/pki/${file}" ]
	then
		result='present'
	fi
done

echo "${result}"
