#!/bin/sh -e

# Return "present" if the CA is present, "absent" otherwise.

pki_dir=$(cat "${__object:?}/parameter/pki-dir")

test -d "${pki_dir}" || {
	echo 'absent'
	exit 0
}

result='absent'

for dir in issued certs_by_serial
do
	if [ -d "${pki_dir}/${dir}" ]
	then
		result='present'
	fi
done

for file in serial index.txt index.txt.attr ca.crt private/ca.key
do
	if [ -f "${pki_dir}/${file}" ]
	then
		result='present'
	fi
done

echo "${result}"
