#!/bin/sh -e

# Return "absent" if no folder 'pki' is present, "present" otherwise.

# TODO could something of this be deduplicated with the __easy_rsa_pki type?

base_dir=$(cat "${__object:?}/parameter/dir")
pki_dir="${base_dir}/pki"

# Do we even have a `pki`-directory?
if [ ! -d "${pki_dir}" ]; then
	echo "absent"
	exit 0
fi
# pki-folder is present, check if everything is all right
expected_folders="private reqs"
for folder in ${expected_folders}; do
	dir="${pki_dir}/${folder}"
	if [ ! -d "${dir}" ]; then
		echo "Missing ${dir}" >&2
		exit 1
	fi
done

# Check for openssl config file
openssl_easyrsa_conf_file="${pki_dir}/openssl-easyrsa.cnf"
if [ ! -f "${openssl_easyrsa_conf_file}" ]; then
	echo "Missing ${openssl_easyrsa_conf_file}" >&2
	exit 1
fi

# Nothing wrong found, return "present"
echo "present"
