#!/bin/sh

# Return "present" if a pki-folder is found, "absent" otherwise.

directory="/${__object_id:?}"
full_dir="${directory}/pki"

# Do we have a clean slate?
if [ ! -d ${full_dir} ]; then
	echo "absent"
	exit 0
fi

# pki-folder is present, check if everything is all right
expected_folders="private reqs"
for folder in ${expected_folders}; do
	dir="${full_dir}/${folder}"
	if [ ! -d "${dir}" ]; then
		echo "Missing ${dir}" >&2
		exit 1
	fi
done

# Check for openssl config file
openssl_easyrsa_conf_file="${full_dir}/openssl-easyrsa.cnf"
if [ ! -f "${openssl_easyrsa_conf_file}" ]; then
	echo "Missing ${openssl_easyrsa_conf_file}" >&2
	exit 1
fi

# Nothing wrong found, return "present"
echo "present"

