#!/bin/sh -e
#
# 2020 Marko Seric (marko.seric at ssrq-sds-fds.ch)
# 2020 Dennis Camera (dennis.camera at ssrq-sds-fds.ch)
# 2020 Beni Ruef (bernhard.ruef at ssrq-sds-fds.ch)
#
# This file is part of cdist.
#
# cdist is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# cdist is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with cdist. If not, see <http://www.gnu.org/licenses/>.
#

quote() { printf "'%s'" "$(printf '%s' "$*" | sed -e "s/'/'\\\\''/g")"; }

base_dir=$(cat "${__object:?}/parameter/dir")

state_is=$(cat "${__object:?}/explorer/cert-presence")

# Set the executable for easy-rsa
easyrsa_executable=
os=$(cat "${__global:?}/explorer/os")
case ${os}
in
	(debian|devuan)
		easyrsa_executable='/usr/share/easy-rsa/easyrsa'
		;;
	(*)
		exit 1  # fail, OS whitelist should be in manifest
		;;
esac

# Check validity of the supplied parameters
# shellcheck source=/dev/null
. "${__type:?}/files/check_parameter_validity.sh"

check_parameter_validity_usealgo

## Check required parameters for sanity
cert_type=$(cat "${__object:?}/parameter/cert-type")
case ${cert_type}
in
	(server|client)
		;;  # These two are okay
	(*)
		echo 'cert-type should be either "server" or "client".' >&2
		exit 1
		;;
esac

req_options=
if test -s "${__object:?}/parameter/common-name"
then
	req_options="--req-cn='$(head -n1 "${__object:?}/parameter/common-name")'"
fi

if test "${state_is}" != 'present'
then
	printf 'cd %s\n' "$(quote "${base_dir}")"

	easyrsa_cmd="${easyrsa_executable} --pki-dir=$(quote "${base_dir}/pki") --vars=$(quote "${base_dir}/vars") --batch"

	printf '%s %s gen-req %s nopass\n' \
		"${easyrsa_cmd}" "${req_options# }" "$(quote "${__object_id:?}")"
	printf '%s sign-req %s %s\n' \
		"${easyrsa_cmd}" "${cert_type}" "$(quote "${__object_id:?}")"
fi
