#!/bin/sh -e

# Return "absent" if no CA present, "present" otherwise

base_dir=$(cat "${__object:?}/parameter/dir")
pki_dir="${base_dir}/pki"

result="absent"


# Check all the files
expected_files_in_pki="serial index.txt index.txt.attr ca.crt private/ca.key"

# Check all the folders
for file in ${expected_files_in_pki}; do
	if [ -f "${pki_dir}/${file}" ]; then
		result="present"
	fi
done

expected_dirs_in_pki="issued certs_by_serial"

for dir in ${expected_dirs_in_pki}; do
	if [ -d "${pki_dir}/${dir}" ]; then
		result="present"
	fi
done

echo ${result}
