#!/bin/sh -e

# Return "present" if there already a cert, "" otherwise

pki_dir=$(cat "${__object:?}/parameter/pki-dir")
common_name=${__object_id:?}

test -f "${pki_dir}/issued/${common_name}.crt" && echo 'present' || echo 'absent'
