#!/bin/sh

# Return "present" if there already a cert, "" otherwise

supplied_dir=$(cat "${__object:?}/parameter/pki-dir")
pki_dir="${supplied_dir}/pki"
common_name="${__object_id:?}"

test -f "${pki_dir}/issued/${common_name}.crt" && echo "present" || echo ""

